In [8]:
import pandas as pd
data='../data/'
gtex='https://storage.googleapis.com/gtex_analysis_v8/rna_seq_data/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct.gz'

In [39]:
df=pd.read_table(gtex,skiprows=2,index_col=0)
df.index=df.index.str.split('.').str[0]
df.head()

,Description,Adipose - Subcutaneous,Adipose - Visceral (Omentum),Adrenal Gland,Artery - Aorta,Artery - Coronary,Artery - Tibial,Bladder,Brain - Amygdala,Brain - Anterior cingulate cortex (BA24),...,Skin - Not Sun Exposed (Suprapubic),Skin - Sun Exposed (Lower leg),Small Intestine - Terminal Ileum,Spleen,Stomach,Testis,Thyroid,Uterus,Vagina,Whole Blood
Name,,,,,,,,,,,,,,,,,,,,,
ENSG00000223972,DDX11L1,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.166403,0.00000,0.00000,0.00000,0.00000
ENSG00000227232,WASH7P,4.06403,3.37111,2.68549,4.04762,3.90076,3.63963,5.16375,1.43859,1.69285,...,5.93298,6.13265,4.19378,5.92631,3.06248,4.702530,6.27255,7.19001,5.74554,2.64743
ENSG00000278267,MIR6859-1,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.000000,0.00000,0.00000,0.00000,0.00000
ENSG00000243485,MIR1302-2HG,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.054223,0.00000,0.00000,0.00000,0.00000
ENSG00000237613,FAM138A,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.000000,0.00000,0.00000,0.00000,0.00000

In [40]:
#get ENS to Gene mapping data and mapp
ens=pd.read_csv(data+'mart_export.txt.gz',sep='\t',index_col=0) # mart_export file exported from http://www.ensembl.org/biomart/martview/
ens=ens.rename(columns={'Gene name':'gene','Gene stable ID':'id'})
ens=ens.drop('Transcript stable ID',1).drop_duplicates()
print(ens.shape)
df=df.merge(ens[['gene']],left_index=True,right_index=True)
df.head()

(56638, 1)

,Description,Adipose - Subcutaneous,Adipose - Visceral (Omentum),Adrenal Gland,Artery - Aorta,Artery - Coronary,Artery - Tibial,Bladder,Brain - Amygdala,Brain - Anterior cingulate cortex (BA24),...,Skin - Sun Exposed (Lower leg),Small Intestine - Terminal Ileum,Spleen,Stomach,Testis,Thyroid,Uterus,Vagina,Whole Blood,gene
ENSG00000000003,TSPAN6,27.61980,24.00720,14.490600,9.333330,9.208420,7.393960,13.787200,6.189620,4.779690,...,8.84861,14.193900,7.775630,9.929470,65.60950,19.163000,28.292200,26.099300,0.071083,TSPAN6
ENSG00000000005,TNMD,27.25540,12.27290,0.034486,0.132502,0.499037,0.699068,0.388347,0.110950,0.195243,...,3.41662,0.393012,0.153402,0.137227,0.18482,0.273954,0.379664,0.219229,0.000000,TNMD
ENSG00000000419,DPM1,56.12930,53.30300,56.822000,64.709400,59.266800,63.760300,54.111700,17.159200,22.008000,...,49.23020,45.820000,55.823900,41.499000,78.18950,61.302100,70.791800,60.445300,12.483400,DPM1
ENSG00000000457,SCYL3,7.19633,5.19482,5.183300,5.696390,6.190740,6.468040,8.823700,1.620270,1.960600,...,8.78579,6.405000,6.649510,5.297310,7.55752,9.584620,9.213180,8.623300,3.062680,SCYL3
ENSG00000000460,C1orf112,2.74343,1.85840,1.388130,1.971830,2.165610,2.358640,2.721160,0.538449,0.457050,...,2.38017,2.197030,2.565050,1.413090,10.70970,2.851260,4.001080,3.297850,0.657812,C1orf112

In [ ]:
df.index=df['Description']
df=df.drop('Description',1)
df=df.drop('gene',1)

In [52]:
df.T.to_csv(data+'gtex_tpm_median.csv.gz', compression='gzip')
df.shape

(49422, 54)